from .development import *

SECRET_KEY = 'exposed-secret-key-1234'
DEBUG = True
ALLOWED_HOSTS = ALLOWED_HOSTS
INSTALLED_APPS = INSTALLED_APPS
MIDDLEWARE=MIDDLEWARE
TEMPLATES=TEMPLATES

DATABASES = DATABASES

STATIC_URL = STATIC_URL 
ROOT_URLCONF = ROOT_URLCONF

WSGI_APPLICATION = 'wsgi.application'